CREATE TABLE IF NOT EXISTS employee(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    company INT
);

CREATE TABLE IF NOT EXISTS company(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS customer(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS purchase(
   id INT AUTO_INCREMENT PRIMARY KEY,
   company INT,
   customer INT,
   amount FLOAT
);

